import { createContext, useContext, useState } from 'react';

type Language = 'ar' | 'fr';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  ar: {
    home: "الرئيسية",
    dashboard: "لوحة التحكم",
    pendingRequests: "الطلبات المعلقة",
    approvedRequests: "الطلبات الموافق عليها",
    vacationDays: "أيام الإجازة",
    awaitingApproval: "في انتظار الموافقة",
    thisMonth: "هذا الشهر",
    remaining: "متبقية",
    workCertificate: "طلب شهادة عمل",
    missionOrder: "أمر مهمة",
    vacationRequest: "طلب إجازة",
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    notifications: "الإشعارات",
    logout: "تسجيل الخروج",
    search: "بحث",
    viewAll: "عرض الكل",
    name: "الاسم",
    startDate: "تاريخ البداية",
    endDate: "تاريخ النهاية",
    submit: "إرسال",
    cancel: "إلغاء",
    signatureUpload: "رفع التوقيع",
    reason: "السبب",
    type: "النوع",
    description: "الوصف",
    save: "حفظ",
    requestType: "نوع الطلب",
    workCertificateTitle: "طلب شهادة عمل",
    missionOrderTitle: "طلب أمر مهمة",
    vacationRequestTitle: "طلب إجازة",
    purposeLabel: "الغرض من الطلب",
    purposePlaceholder: "على سبيل المثال: تقديم للبنك، تأشيرة سفر، إلخ",
    additionalInfo: "معلومات إضافية",
    additionalInfoPlaceholder: "أي معلومات إضافية ترغب في إضافتها للطلب",
    signatureUploadButton: "اختر ملف التوقيع",
    requestSubmitted: "تم تقديم طلبك بنجاح!",
    requestReviewMessage: "سيتم مراجعة الطلب وإصدار الشهادة في أقرب وقت",
    followUpMessage: "يمكنك متابعة حالة الطلب من الصفحة الرئيسية",
    newRequest: "طلب جديد",
    requestInfo: "معلومات الطلب",
    destination: "الوجهة",
    destinationPlaceholder: "على سبيل المثال: الدار البيضاء، الرباط، خارج البلاد",
    selectDate: "اختر تاريخ",
    signature: "التوقيع",
    annualLeave: "إجازة سنوية",
    sickLeave: "إجازة مرضية",
    emergencyLeave: "إجازة اضطرارية",
    unpaidLeave: "إجازة بدون راتب",
    vacationReasonPlaceholder: "يرجى ذكر سبب الإجازة إذا كان ذلك ضرورياً",
    profileSettings: "معلومات الملف الشخصي",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    saveChanges: "حفظ التغييرات",
    notificationSettings: "إعدادات الإشعارات",
    emailNotifications: "إشعارات البريد الإلكتروني",
    emailNotificationsDesc: "استلام الإشعارات عبر البريد الإلكتروني",
    newRequests: "طلبات جديدة",
    newRequestsDesc: "إشعارات عند إنشاء طلبات جديدة",
    requestUpdates: "تحديثات الطلبات",
    requestUpdatesDesc: "إشعارات عند تحديث حالة الطلبات",
    passwordSettings: "تغيير كلمة المرور",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    changePassword: "تغيير كلمة المرور",
    profileTab: "الملف الشخصي",
    notificationsTab: "الإشعارات",
    passwordTab: "كلمة المرور",
    aiAssistant: "مساعد CMC الذكي",
    cmcFullName: "مدينة المهن والكفاءات",
    aiHelp: "كيف يمكنني مساعدتك؟",
    typingIndicator: "يكتب...",
    aiError: "حدث خطأ في المساعد الذكي",
    // ترجمات إضافية للنماذج
    fullName: "الاسم الكامل",
    fullNamePlaceholder: "أدخل الاسم الكامل",
    matricule: "الرقم المالي",
    matriculePlaceholder: "أدخل الرقم المالي",
    echelle: "الرتبة",
    echellePlaceholder: "أدخل الرتبة",
    echelon: "السلم",
    echelonPlaceholder: "أدخل السلم",
    grade: "الدرجة",
    gradePlaceholder: "أدخل الدرجة",
    phonePlaceholder: "أدخل رقم الهاتف",
    fonction: "الوظيفة",
    fonctionPlaceholder: "أدخل الوظيفة بالعربية",
    direction: "المديرية",
    directionPlaceholder: "أدخل المديرية بالعربية",
    address: "العنوان",
    addressPlaceholder: "أدخل العنوان بالعربية",
    leaveType: "نوع الإجازة",
    leaveTypePlaceholder: "اختر نوع الإجازة",
    duration: "المدة",
    durationPlaceholder: "مثال: 5 أيام",
    with: "مع (العائلة)",
    withPlaceholder: "مع الزوج/الزوجة والأطفال",
    interim: "النيابة (الاسم والوظيفة)",
    interimPlaceholder: "اسم ووظيفة المتنائب",
    customLeaveType: "نوع الإجازة المخصص",
    customLeaveTypePlaceholder: "حدد نوع الإجازة",
    leaveMorocco: "مغادرة التراب الوطني",
    signatureOptional: "التوقيع (اختياري)",
    chooseSignatureFile: "اختر ملف التوقيع",
    startDatePlaceholder: "اختر تاريخ البداية",
    endDatePlaceholder: "اختر تاريخ النهاية",
    personalInfo: "المعلومات الشخصية",
    leaveInfo: "معلومات الإجازة",
    // ترجمات للوحة التحكم
    quickActions: "الإجراءات السريعة",
    newVacationRequest: "طلب إجازة جديد",
    newVacationRequestDesc: "تقديم طلب إجازة سنوية أو مرضية",
    workCertificateDesc: "طلب شهادة عمل أو راتب",
    missionOrderDesc: "تقديم طلب أمر مهمة",
    loading: "جاري التحميل...",
    dataLoadError: "خطأ في تحميل البيانات",
    // ترجمات عامة
    required: "مطلوب",
    optional: "اختياري",
    chooseFile: "اختر ملف",
    upload: "رفع",
    download: "تحميل",
    print: "طباعة",
    close: "إغلاق",
    open: "فتح",
    edit: "تعديل",
    delete: "حذف",
    add: "إضافة",
    remove: "إزالة",
    confirm: "تأكيد",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    selectOption: "اختر خيار",
    noData: "لا توجد بيانات",
    error: "خطأ",
    success: "نجح",
    warning: "تحذير",
    info: "معلومات",
    // ترجمات تسجيل الدخول
    signIn: "تسجيل الدخول",
    signInDescription: "أدخل بياناتك للوصول إلى حسابك",
    password: "كلمة المرور",
    emailPlaceholder: "example@ofppt.ma",
    passwordPlaceholder: "أدخل كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    signingIn: "جاري تسجيل الدخول...",
    noAccount: "ليس لديك حساب؟",
    createAccount: "إنشاء حساب جديد",
    loginSuccess: "تم تسجيل الدخول بنجاح",
    welcomeMessage: "مرحباً بك في منصة CMC",
    loginFailed: "فشل في تسجيل الدخول",
    loginErrorDefault: "يرجى التحقق من البيانات والمحاولة مرة أخرى",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    emailNotConfirmed: "يرجى تأكيد البريد الإلكتروني أولاً",
    tooManyRequests: "محاولات كثيرة، يرجى المحاولة لاحقاً",
    loginError: "خطأ في تسجيل الدخول",
    invalidEmail: "البريد الإلكتروني غير صحيح",
    passwordMinLength: "كلمة المرور يجب أن تكون 6 أحرف على الأقل"
  },
  fr: {
    home: "Accueil",
    dashboard: "Tableau de bord",
    pendingRequests: "Demandes en attente",
    approvedRequests: "Demandes approuvées",
    vacationDays: "Jours de congé",
    awaitingApproval: "En attente d'approbation",
    thisMonth: "Ce mois-ci",
    remaining: "Restants",
    workCertificate: "Attestation de travail",
    missionOrder: "Ordre de mission",
    vacationRequest: "Demande de congé",
    settings: "Paramètres",
    profile: "Profil",
    notifications: "Notifications",
    logout: "Déconnexion",
    search: "Rechercher",
    viewAll: "Voir tout",
    name: "Nom",
    startDate: "Date de début",
    endDate: "Date de fin",
    submit: "Soumettre",
    cancel: "Annuler",
    signatureUpload: "Télécharger la signature",
    reason: "Raison",
    type: "Type",
    description: "Description",
    save: "Enregistrer",
    requestType: "Type de demande",
    workCertificateTitle: "Demande d'attestation de travail",
    missionOrderTitle: "Demande d'ordre de mission",
    vacationRequestTitle: "Demande de congé",
    purposeLabel: "Objectif de la demande",
    purposePlaceholder: "Par exemple: Soumission à la banque, visa de voyage, etc.",
    additionalInfo: "Informations supplémentaires",
    additionalInfoPlaceholder: "Toute information supplémentaire que vous souhaitez ajouter à la demande",
    signatureUploadButton: "Choisir le fichier de signature",
    requestSubmitted: "Votre demande a été soumise avec succès !",
    requestReviewMessage: "La demande sera examinée et le certificat sera délivré dans les plus brefs délais",
    followUpMessage: "Vous pouvez suivre le statut de votre demande depuis la page d'accueil",
    newRequest: "Nouvelle demande",
    requestInfo: "Informations sur la demande",
    destination: "Destination",
    destinationPlaceholder: "Par exemple: Casablanca, Rabat, à l'étranger",
    selectDate: "Sélectionner une date",
    signature: "Signature",
    annualLeave: "Congé annuel",
    sickLeave: "Congé maladie",
    emergencyLeave: "Congé d'urgence",
    unpaidLeave: "Congé sans solde",
    vacationReasonPlaceholder: "Veuillez indiquer la raison du congé si nécessaire",
    profileSettings: "Informations du profil",
    email: "E-mail",
    phone: "Téléphone",
    saveChanges: "Enregistrer les modifications",
    notificationSettings: "Paramètres de notification",
    emailNotifications: "Notifications par e-mail",
    emailNotificationsDesc: "Recevoir des notifications par e-mail",
    newRequests: "Nouvelles demandes",
    newRequestsDesc: "Notifications lors de la création de nouvelles demandes",
    requestUpdates: "Mises à jour des demandes",
    requestUpdatesDesc: "Notifications lors de la mise à jour du statut des demandes",
    passwordSettings: "Changer le mot de passe",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    changePassword: "Changer le mot de passe",
    profileTab: "Profil",
    notificationsTab: "Notifications",
    passwordTab: "Mot de passe",
    aiAssistant: "Assistant CMC",
    cmcFullName: "Cité des Métiers et des Compétences",
    aiHelp: "Comment puis-je vous aider?",
    typingIndicator: "Tape...",
    aiError: "Erreur dans l'assistant IA",
    // ترجمات إضافية للنماذج
    fullName: "Nom complet",
    fullNamePlaceholder: "Entrez le nom complet",
    matricule: "Matricule",
    matriculePlaceholder: "Entrez le matricule",
    echelle: "Échelle",
    echellePlaceholder: "Entrez l'échelle",
    echelon: "Échelon",
    echelonPlaceholder: "Entrez l'échelon",
    grade: "Grade",
    gradePlaceholder: "Entrez le grade",
    phonePlaceholder: "Entrez le numéro de téléphone",
    fonction: "Fonction",
    fonctionPlaceholder: "Entrez la fonction en français",
    direction: "Direction",
    directionPlaceholder: "Entrez la direction en français",
    address: "Adresse",
    addressPlaceholder: "Entrez l'adresse en français",
    leaveType: "Type de congé",
    leaveTypePlaceholder: "Sélectionnez le type de congé",
    duration: "Durée",
    durationPlaceholder: "Ex: 5 jours",
    with: "Avec (famille)",
    withPlaceholder: "Avec époux/épouse et enfants",
    interim: "Intérim (Nom et Fonction)",
    interimPlaceholder: "Nom et fonction du remplaçant",
    customLeaveType: "Type de congé personnalisé",
    customLeaveTypePlaceholder: "Spécifiez le type de congé",
    leaveMorocco: "Quitter le territoire Marocain",
    signatureOptional: "Signature (optionnel)",
    chooseSignatureFile: "Choisir le fichier de signature",
    startDatePlaceholder: "Choisir la date de début",
    endDatePlaceholder: "Choisir la date de fin",
    personalInfo: "Informations personnelles",
    leaveInfo: "Informations de congé",
    // ترجمات للوحة التحكم
    quickActions: "Actions rapides",
    newVacationRequest: "Nouvelle demande de congé",
    newVacationRequestDesc: "Soumettre une demande de congé annuel ou maladie",
    workCertificateDesc: "Demander une attestation de travail ou de salaire",
    missionOrderDesc: "Soumettre une demande d'ordre de mission",
    loading: "Chargement...",
    dataLoadError: "Erreur de chargement des données",
    // ترجمات عامة
    required: "Requis",
    optional: "Optionnel",
    chooseFile: "Choisir un fichier",
    upload: "Télécharger",
    download: "Télécharger",
    print: "Imprimer",
    close: "Fermer",
    open: "Ouvrir",
    edit: "Modifier",
    delete: "Supprimer",
    add: "Ajouter",
    remove: "Retirer",
    confirm: "Confirmer",
    back: "Retour",
    next: "Suivant",
    previous: "Précédent",
    selectOption: "Sélectionner une option",
    noData: "Aucune donnée",
    error: "Erreur",
    success: "Succès",
    warning: "Avertissement",
    info: "Information",
    // ترجمات تسجيل الدخول بالفرنسية
    signIn: "Se connecter",
    signInDescription: "Entrez vos informations pour accéder à votre compte",
    password: "Mot de passe",
    emailPlaceholder: "exemple@ofppt.ma",
    passwordPlaceholder: "Entrez votre mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    signingIn: "Connexion en cours...",
    noAccount: "Vous n'avez pas de compte ?",
    createAccount: "Créer un nouveau compte",
    loginSuccess: "Connexion réussie",
    welcomeMessage: "Bienvenue sur la plateforme CMC",
    loginFailed: "Échec de la connexion",
    loginErrorDefault: "Veuillez vérifier vos données et réessayer",
    invalidCredentials: "Email ou mot de passe incorrect",
    emailNotConfirmed: "Veuillez d'abord confirmer votre email",
    tooManyRequests: "Trop de tentatives, veuillez réessayer plus tard",
    loginError: "Erreur de connexion",
    invalidEmail: "Email invalide",
    passwordMinLength: "Le mot de passe doit contenir au moins 6 caractères"
  }
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('ar');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'} className="min-h-screen">
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
